version: 2
jobs:
  build:
    docker:
      - image: circleci/node@sha256
      - image: debian:stretch       

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
      
      - run:
          name: npm-install
          command: npm install
          
      - run:
          name: npm-test
          command: npm test
