version: 3.4
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Setup Variables
          command: |
           if [ $CIRCLE_BRANCH = 'staging' ] || [ $CIRCLE_BRANCH = 'master' ]; then
           echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
           echo 'export IMAGE_NAME=${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}' >> $BASH_ENV
           fi
      - run:
          name: Build and push Docker image
          command: |
           if [ $CIRCLE_BRANCH = 'staging' ] || [ $CIRCLE_BRANCH = 'master' ]; then
           docker build -t $DOCKER_ORG/$IMAGE_NAME:$TAG -f $(pwd)/.circleci/Dockerfile .
           echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
           docker push $DOCKER_ORG/$IMAGE_NAME:$TAG
           fi