version: 3.4
jobs:
  build:
    docker:
      - image: circleci/golang:1.11-node
      - image: debian:stretch 
    working_directory: ~/code 

    steps:
      - checkout    

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
      
      - run:
          name: npm-install
          command: npm install
          
      - run:
          name: npm-test
          command: npm test
      - run:
          name: Setup Variables
          command: |
          if [ $CIRCLE_BRANCH == 'staging' ] || [ $CIRCLE_BRANCH == 'master' ]; then
          echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
          echo 'export IMAGE_NAME=${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}' >> $BASH_ENV
          fi
       - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
          if [ $CIRCLE_BRANCH == 'staging' ] || [ $CIRCLE_BRANCH == 'master' ]; then
          docker build -t $DOCKER_ORG/$IMAGE_NAME:$TAG .
          echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push $DOCKER_ORG/$IMAGE_NAME:$TAG
          fi
